### PR TITLE
eth/tracers: replace hardcoded txGas with actual

### PR DESCRIPTION
**Pull request by s1na**
So a few comments here:

- I needed `isHomestead` and `isIstanbul` values and didn't store them in the `ctx` map because that would expose them to js. So stored them in the `Tracer` struct instead
- My bindata output seems different. It might be because I'm using `v3.1.2`? which version do you use?
- Also I still need to rebase master to fix the merge conflicts

### CODE REVIEW

**Comment by holiman** [comment]
How about  setting 'intrinsicGas' as another param on the ctx, instead of adding it to gasUsed. The way you did it makes certain usecases work better, and other usecases regress (if one doesn't care about intrinsic, but just wants the gas used by the execution).Also it's a bit unintuitive that the go-method CaptureEnd gets a gasUsed as input, but that's not what the JsTracer sees. So I'd pefert a second field personally

**Comment by s1na** [comment]
> How about  setting 'intrinsicGas' as another param on the ctx, instead of adding it to gasUsed.

Makes sense, I'll do that

> So I'd pefert a second field personally

Just to clarify, you're saying we should compute intrinsicGas in `evm.go` and pass it to `CaptureEnd` (in addition to the current `gasUsed`)? I can do that

**Comment by holiman** [comment]
Just to clarify, you're saying we should compute intrinsicGas in evm.go and pass it to CaptureEnd (in addition to the current gasUsed)? I can do that

Actually I didn't mean that, I meant that the js thingy would calculate it, like you did, and set it inside the javascript-object. But the other way might work aswell, but have larger ramifications.

**Comment by s1na** [comment]
> Actually I didn't mean that, I meant that the js thingy would calculate it, like you did, and set it inside the javascript-object. But the other way might work aswell, but have larger ramifications.

Sorry I had misunderstood and thought this is a different point from `intrinsicGas` in ctx.

Fixed that issue now, but I messed up the PR...I merged master into this branch to fix the conflicts but now it has a massive diff which makes it hard to review, sorry. Any ideas?

**Comment by holiman** [comment]
> Fixed that issue now, but I messed up the PR...I merged master into this branch to fix the conflicts but now it has a massive diff which makes it hard to review, sorry. Any ideas?

Yep, here's what we do 

```
git rebase -i eth/master 
```

Well, depending on how you have it configured. I recommend having `eth` or `upstream` as go-ethereum, and `origin` be your own fork. 
After that, 
```
git push -f
```
To push it to your branch

**Comment by s1na** [comment]
Thanks. I chose the easy way and used merge instead of rebase...I've now rebased but this PR still has the massive diff I think because it has a different history from Guillaume's branch. I created a fresh PR https://github.com/ethereum/go-ethereum/pull/22038 directly against master. Will close this afterwards.

**Pull request closed without merging**
